Loops
jonddoe/c-sharp-basics pull request #4
Opened 2021-04-11 12:09 UTC by jonddoe

2021-04-14 17:02 UTC, ausmoons requested changes

2021-04-14 17:02 UTC, ausmoons commented on Loops/Loops/Exercise3/Models/Test.cs
> +    class Test
Kas ir šis?

2021-04-14 17:02 UTC, ausmoons commented on Loops/Loops/Exercise6/Program.cs
> +
Tas ir viens if else, nevajag atstarpes..tikai beigās pēc pēdējā else iekš viena if else

2021-04-14 17:02 UTC, ausmoons commented on Loops/Loops/Exercise7/Program.cs
> +                    if (rolledValue == 1)
šeit vai tad nevar būt if else?

2021-04-14 17:02 UTC, ausmoons commented on Loops/Loops/Exercise7/Program.cs
> +                if (answer == "y")
Vai tad jau lielais if nav tāds pats?

2021-04-14 17:02 UTC, ausmoons commented on Loops/Loops/Test/Program.cs
> +            //for (var t = 0; t < 3; ++t)
Kas ir šis?

2021-04-15 22:09 UTC, jonddoe commented on Loops/Loops/Exercise7/Program.cs
> +                if (answer == "y")
Nē itkā.. Šo izsauc kad nav uzmests 1, ir uzspiests n, spēle ir beigta un prasa vai sākt jaunu spēli

2021-04-16 06:31 UTC, ausmoons approved these changes

2021-04-16 11:00 UTC, merged